### ISSUE TITLE
Why we should reset references in the loader ?

### ISSUE THREAD

**Issue by ivanche** [hautelook/AliceBundle#182]
I'm trying to get the loaded objects (references) in my phpunit test after the loading fixtures, but i don't understand how to get them.
I tried to get references through service 'hautelook_alice.alice.fixtures.loader', but it's empty.
[There](https://github.com/hautelook/AliceBundle/blob/v1.1.0/src/Alice/DataFixtures/Fixtures/Loader.php#L51) we reset references. Okay, so let's say us need it.
But [there](https://github.com/hautelook/AliceBundle/blob/v1.1.0/src/Doctrine/DataFixtures/Executor/ExecutorTrait.php#L41) returned the void and we don't receive the loaded objects again ...I'm confused.
Help me please. And sorry for my English :)

**Comment by theofidry** [comment]
Ha, that's because you are looking at the wrong loader :)

The loader you gave actually load a fixture file into an array of objects. Maybe that's what you want after all, but otherwise you should use 'hautelook_alice.fixtures.loader', which takes care of the persitence, processors, besides being able to load multiple files.

You should get the loaded objects not via the references but by the array returned by the `load()` function.

'hautelook_alice.fixtures.loader' is meant to be used if you know which files you're loading, letting you the responsibility of providing the files. Otherwise if you want something more automated, you should try to run the command instead (it is possible to run a console command in your PHPUnit test) or roll out your own service that takes care of retrieving files before giving them to the loader. If you want to do so, you should take a look at [Finder\FixturesInterface](https://github.com/hautelook/AliceBundle/blob/v1.1.0/src/Finder/FixturesFinderInterface.php).

Note that the logic should then be similar to what is happening in the command. But the command is slightly more complex to support Doctrine DataFixturesLoaders.

If there is still something unclear for you don't hesitate to ask.

**Comment by ivanche** [comment]
Thanks for fast answer.
I forgot to say i run the console command in my phpunit test.
In version 0.2 i used following way:
before every test i execute method
```php
    public function prepareEnvironment(KernelInterface $kernel, $recreateSchema = true)
    {
        static::$application = new Application($kernel);
        static::$application->setAutoExit(false);
        if ($recreateSchema) {
            $this->runConsole("doctrine:schema:drop", array("--force" => true));
            $this->runConsole("doctrine:schema:create");
        }
        $this->runConsole("doctrine:fixtures:load");
        self::$em = $kernel->getContainer()->get('doctrine.orm.entity_manager');
        self::$alice = $kernel->getContainer()->get('hautelook_alice.loader');
    }
```
and inside test i used code in order to get loaded object
```php
    public function testCreateRecipient()
    {
        // Some code ...

        $fixture = static::$alice->getReferences()['order_gas_saver_4'];
        $entity = static::$em->find('AppBundle:Order', $fixture->getId());

        $this->assertEquals(2, $entity->getSequenceStatus());
    }
```
It was useful. New version don't have analogs.
In version 0.2 the references stored in [loader](https://github.com/hautelook/AliceBundle/blob/0.2/Alice/Loader.php#L110).

IMO in version 1 the references must be stored [there](https://github.com/hautelook/AliceBundle/blob/master/src/Alice/DataFixtures/Loader.php#L110), i.e. after persist objects we add references in property "references" in class Hautelook\AliceBundle\Alice\DataFixtures\Loader.
What do you think about it ? I can do it after while.

**Comment by theofidry** [comment]
Sorry for the late answer. I am not really to keen to do that as it would result in a transient state.

IMO you shouldn't need to do that, your objects are persisted so you can retrieve them as you need to. If it is really a need for your, you could always create your own loader which decorates this one.
