### ISSUE TITLE
Load fixtures in two differents DB

### ISSUE THREAD

**Issue by Jerome1337** [hautelook/AliceBundle#199]
I'm using AliceBundle with DoctrineFixtureBundle and I'm trying to load fixtures in 2 differents database with some relations in each other.

When I'm trying to add these new fixtures

```
PowerDNSBundle\Entity\PowerDNSDomain:
    power_dns_domain_{0..50}:
        name: <freeEmailDomain()>
        ownerId: <numberBetween(1, 10)>x @AppBundle/DataFixtures/ORM/user_customer_*
```

I get this error during the loading

> The class 'PowerDNSBundle\Entity\PowerDNSDomain' was not found in the chain configured namespaces AppBundle\Entity, Gedmo\Translatable\Entity, Gedmo\Translator\Entity, Gedmo\Loggable\Entity, Gedmo\Tree\Entity, FOS\OAuthServerBundle\Entity, FOS\UserBundle\Model

There is a way to load fixtures in two differents DB with relation like this ?

Thanks,

**Comment by vincentchalamon** [comment]
The error tells you your entity has not been found in your manager mapping. I guess you have configured 2 managers in your doctrine configuration: `default` with `AppBundle` and another one with `PowerDNSBundle` ?

In order to load your data, you should separate your fixtures using different Symfony environments. For example:
- *src/AppBundle/DataFixtures/ORM/dev/user_customer.yml*
- *src/PowerDNSBundle/DataFixtures/ORM/foo/power_dns_domain.yml*

Configure a `app/config/config_foo.yml` file which loads `config_dev.yml`, then you should be able to load your fixtures through following commands:
```bash
# This one will load your fixtures for default environment (dev) using default manager (default)
php app/console hautelook_alice:doctrine:fixtures:load

# This one will load your fixtures for foo environment using custom manager named `foo`
php app/console hautelook_alice:doctrine:fixtures:load --env=foo --manager=foo
```

AliceBundle will look for fixtures in environment directory like *src/YourBundle/DataFixtures/ORM/{environment}*. So the first command will load data on *src/AppBundle/DataFixtures/ORM/dev* directory, and the second one from *src/PowerDNSBundle/DataFixtures/ORM/foo* :)

The bad news is that AliceBundle (& Symfony neither) shouldn't be able to *do the magic trick* to detect the id of your UserCustomer and set it as an association in your PowerDNSDomain entity, as it's from a different command / environment / manager. So you should set it manually like:
```yml
PowerDNSBundle\Entity\PowerDNSDomain:
    power_dns_domain_{0..50}:
        name: <freeEmailDomain()>
        ownerId: <numberBetween(1, 10)>
```

(The id should always be the same if you use `--purge-with-truncate` option on the command).

**Comment by Jerome1337** [comment]
Exactly
> I guess you have configured 2 managers in your doctrine configuration: default with AppBundle and another one with PowerDNSBundle ?

Anyway this is working perfectly.
Thanks.
