### ISSUE TITLE
Is there a way to reference entities by Id without guessing it

### ISSUE THREAD

**Issue by thedamnedrhino** [hautelook/AliceBundle#241]
I want to reference a specific Entity in my Fixtures. Now I can't use the Repository to find it by it's Fields, since they might change in my tests, e.g: when I test my forms. What's the best way to handle this, beside guessing the `id` to be e.g: `1`, since it's the first Entry in the Fixture File?

**Comment by theofidry** [comment]
>I can't use the Repository to find it by it's Fields, since they might change in my tests

Then what makes this record special? If it changes so much that you can't pick it by a distinct field, maybe it doesn't matter which entity you actually are using?

>beside guessing the id to be e.g: 1, since it's the first Entry in the Fixture File?

Guessing the ID is usually a bad idea: if you reload your fixtures set without dropping the DB the auto-increment ID will not give you the same IDs as before.

I'm lacking a bit of context, but my guess is that you are loading a set of fixtures for doing integration tests, and your problem is that sometimes you want to be able to pick a specific fixture which is subject to change during the testing phase.

I have no silver bullet solution to that, and it depends of your application, be here's a couple of solutions that come to my mind:

- Isolate your tests: if you're testing two scenarios, it's often easier to restart from "clean" state, i.e. dropping and reloading the DB between each scenarios or between groups of scenarios
- Don't have a global set of fixtures for your tests: it quickly leads to very big fixtures set, hard to manage, with specific fixtures used left and right making it hard to change without causing any side-effect. For my own sanity, I personally like to have very small and specific set of datas for each scenario. As a result, that this set of fixtures is for this scenario only, and this other set is for another scenario. It is much easier to manage (less side-effects), you have more control on your fixtures and it's faster to reload (less fixtures to load).

A consequence of the second point is that it allows you to identifier more easily a specific fixture. If you really want to handle it by ID, then there is one simple solution: make sure this "ID" is not auto-generated, i.e. that you can set it manually. I don't like this solution in general, but it works better if you have UUIDs besides IDs (i.e. UUIDS are the "public IDs" whereas IDs are only for the database and shouldn't be given to the external users).

**Comment by thedamnedrhino** [comment]
Interesting, thanks.

**Comment by aledeg** [comment]
@thedamnedrhino You should follow what @theofidry is saying. Those are some wise words. I went to the wrong path he described. The one with the big fixtures. This is really hard to manage in the long run. You will end with side effects when modifying those files.
My 2¢

**Comment by zhil** [comment]
@theofidry it would be cool to have ability to reference some entity. Something like
```
Vendor\SomeBundle\Entity\SomeEntity:
    field1: 'asdasd'
    field2: 123
    @id: 'homePageTest-SomeEntityUniqueReference'
```

fixture loader could set memcache variable with actual id for key 'homePageTest-SomeEntityUniqueReference' or something like that

**Comment by theofidry** [comment]
@zhil I don't that would be a good idea, first you would require a cache layer to make it work and second this would break from a DB platform to another and could also break with the same DB platform depending on how the DB is reset.

Overall, don't use auto-generated IDs if you want to manipulate them. In raw PHP it's awkward, in fixtures declared in a more abstract way it's even worse. Either use pre-defined IDs like UUIDs or manipulate objects, not IDs

**Comment by gullij** [comment]
@theofidry Hope I'm not reopening this by asking for a little clarification about one thing you say above:

> "For my own sanity, I personally like to have very small and specific set of datas for each scenario."

I'm **very** interested in this, how would you manage this with AliceBundle? I'm guessing I've missed some part of the documentation but I can't recall seeing anything resembling this.

**Comment by theofidry** [comment]
I'm relying on https://github.com/theofidry/AliceDataFixtures, AliceBundle is more for a one time loading fixtures say for integration tests for example IMO cf. https://github.com/hautelook/AliceBundle#when-to-use-this-bundle

**Comment by gullij** [comment]
Thanks! Will dig into this.
