### ISSUE TITLE
How to create a loader compatible with php app/console doctrine:fixtures:load ?

### ISSUE THREAD

**Issue by numerogeek** [hautelook/AliceBundle#252]
Hello,

it seems that a recent released has changed from my previous use case, and the [doc](
https://github.com/hautelook/AliceBundle/blob/master/doc/doctrine-fixtures-bundle.md
) is unclear for me 

I used to make my loader like : 

```

use Hautelook\AliceBundle\Alice\DataFixtureLoader;

class AppFixtures extends DataFixtureLoader
{
    protected function getFixtures()
    {
        return array(
            __DIR__.'/data/categories.yml',
    ]
}
```
and load them with php app/console do:fi:lo, but it seems that it don't work anymore.

How can I make it work the same way that I used to ?

**Comment by theofidry** [comment]
Just by using AliceBundle command instead of DoctrineDataFixtures, i.e. `fixtures:load` :)

You should also be aware that AliceBundle *and* DoctrineDataFixtures are quite redundant. The compatibility has somehow been kept in AliceBundle 1.x to ease the upgrade to the stable release, but this compatibility layer will be completely removed in 2.x.
