### ISSUE TITLE
doctrine:fixtures:load and hautelook/AliceBundle

### ISSUE THREAD

**Issue by LPodolski** [hautelook/AliceBundle#275]
doctrine:fixtures:load does not seem to to load yml fixtures of this bundle

my questions are:
In new version, it is supported that alice fixtures work side by side with doctrine fixtures? by this I mean that you can have some fixtures in alice fixture's yml files, and some in doctrine fixtures?

is it supported that you can reference doctrine fixtures in alice fixtures, and the other way around?

in older versions I think this worked out of the box, you has been able to load yml files, if u needed u can even apply ordered interface of doctrine fixtures to run alice & doctrine fixures in order you want, something like this

```
// src/AppBundle/DataFixtures/ORM/AppFixtures.php
namespace AppBundle\DataFixtures\ORM;

use Hautelook\AliceBundle\Alice\DataFixtureLoader;
use Nelmio\Alice\Fixtures;

class AppFixtures extends DataFixtureLoader
{
    /**
     * {@inheritDoc}
     */
    protected function getFixtures()
    {
        return  array(
            __DIR__ . '/test.yml',
        );
    }
}
```

code from this tutorial: https://knpuniversity.com/screencast/alice-fixtures/fixtures

there are still in code base examples of this kind of use cases like:
https://github.com/hautelook/AliceBundle/blob/master/fixtures/Functional/TestBundle/Bundle/CBundle/Resources/fixtures/DataLoader.php

but they seem to be abandoned, because in current code there is no implementation of:
Hautelook\AliceBundle\Doctrine\DataFixtures\AbstractLoader

**Comment by theofidry** [comment]
Nay, support for Doctrine fixtures have been removed in 2.x as mentioned in [the upgrade guide](https://github.com/hautelook/AliceBundle/blob/master/UPGRADE.md#from-1x-to-2x). There is some references left in the codebase but they should be removed.

The support for doctrine fixtures has been kept for convenience and easy upgrade to the first stable version 1.0.0, but it's been just a headache overall and as the systems are a bit redundant, there is not much point to keep them for 2.x.

If you have objects you want to create by yourself, you're free to inject them during the loading of your files, and if you want to do it automatically, you can always decorate this bundle loader to include your files, or maybe use PHP files instead of YAML.
