### ISSUE TITLE
Fixtures load is very slow

### ISSUE THREAD

**Issue by robertosanval** [hautelook/AliceBundle#291]
Hi!

I've a fresh symfony installation 3.1.8 with FOSUserBundle. I've created a simple fixtures.yml file with this content:

```
AppBundle\Entity\User:
    user_{1..10}:
        username: '<username()>'
        plain_password: 'user_<current()>'
        email: '@user_<current()>\@example.local'
        roles: [ROLE_USER]
        enabled: true
```

This takes 32 seconds to execute in a local machine, I think that this is excessive.

```
$ time php bin/console hautelook:fixtures:load -v
Careful, database will be purged. Do you want to continue y/N ?y

real	0m32.858s
user	0m25.999s
sys	0m0.450s
```

What do you think?

**Comment by theofidry** [comment]
Only that takes 32 seconds? That indeed looks more than excessive considering alice itself takes about 5sec for generating your objects. I expect the bottleneck to be the ORM, but for 10 objects 20sec is way too much there's something wrong. Is there any way to provide a Blackfire profile or access to the code?

**Comment by robertosanval** [comment]
I've done some test and the problem is with `FOSUSerBundle` the other fixtures load really fast, only if I create Users the fixtures load are slow.

**Comment by theofidry** [comment]
Let's keep it open then it's worth investigating :)

**Comment by slashfan** [comment]
@robertosanval Hi, which password encoder is configured for your User entity ? I had the same problem loading users and it turned out to be because of the password encoder algorithm.

The recommended **bcrypt** encoder is known to be really slow compared to plaintext (obviously) or sha512 and others (you can make comparisons using the bin/console security:encode-password). As an example, on my dev machine it takes about **0m0.790s** to encode a single password (only 0m0.193s using sha512) using this command.

As I need to **load fixtures for functional tests** I found a workaround by overriding the encoder to plaintext in the test environment. 

Hope it helps !

**Comment by robertosanval** [comment]
Thanks @slashfan I thought that bcrypt was simpler and therefore faster than sha512 or any other.

I've tested my Fixtures with both options:

bcrypt:
```
$ time php bin/console hautelook:fixtures:load -n

real	0m12.257s
user	0m6.237s
sys	0m0.169s
```

sha512:
```
$ time php bin/console hautelook:fixtures:load -n

real	0m6.899s
user	0m1.098s
sys	0m0.235s
```

sha512 is much faster than bcrypt. Thanks for your help!

**Comment by slashfan** [comment]
Good to know ! Keep in mind that bcrypt is much more secure than sha512 and others, so you should keep it for the production environment.

**Comment by theofidry** [comment]
if you are using the right algorithm in SHA512 it's ok. Point is I don't believe your choice of algorithm should be decided on speed for fixtures, just switch to plain text for tests :)

**Comment by m4tthumphrey** [comment]
So really this isn't an issue with Alice as I'm presuming this issue will be there for any type of fixture?

**Comment by theofidry** [comment]
No indeed, I think we can close this now :)
