### ISSUE TITLE
--purge-with-truncate don't work as expected

### ISSUE THREAD

**Issue by robertosanval** [hautelook/AliceBundle#292]
Hi again!

I'm trying to use `--purge-with-truncate` but it doesn't reset the `AUTO_INCREMENT` value.

Is there any way to solve this?

Thanks

**Comment by theofidry** [comment]
Hi, the truncate precisely achieve that: truncating the tables simple **empty** them so they keep memory their `AUTO_INCREMENT` value :)

**Comment by vetal2409** [comment]
Yes, it doesn't work (for mysql in my case).
The method Fidry\AliceDataFixtures\Loader\PurgerLoader:load  doesn't get $purgeMode as argument, therefore it use create mode:
`
if (null === $purgeMode) {
            $purgeMode = PurgeMode::createDeleteMode();
        }
`

**Comment by vetal2409** [comment]
@theofidry [https://github.com/theofidry/AliceDataFixtures/pull/32](https://github.com/theofidry/AliceDataFixtures/pull/32)

**Comment by theofidry** [comment]
Thanks for looking into it, I've checked your PR but I may need to look more thoroughly into it which I'll try to do this evening or tomorrow

**Comment by vetal2409** [comment]
@theofidry Thank you for your well job!

**Comment by vladimirkr** [comment]
This bug steel appears.
When I execute: php bin/console hautelook:fixtures:load --purge-with-truncate
- no errors appears
- command executes with PurgeMode::createDeleteMode instead of PurgeMode::createTruncateMode

If I change string vendor/hautelook/alice-bundle/src/Loader/DoctrineOrmLoader.php:174:
return $loader->load($files, $parameters);
to:
return $loader->load($files, $parameters, [], PurgeMode::createTruncateMode());

I receive: An exception occurred while executing 'TRUNCATE blablabla':               
  SQLSTATE[42000]: Syntax error or access violation...

**Comment by theofidry** [comment]
@vladimirkr do you mind checking the version used?

**Comment by vladimirkr** [comment]
I installed it with your command:
composer require --dev hautelook/alice-bundle:^2.0@beta \
  nelmio/alice:^3.0@beta \
  theofidry/alice-data-fixtures:^1.0@beta \
  doctrine/data-fixtures

**Comment by theofidry** [comment]
@vladimirkr yes but depending on when you ran that command it may give different results... You can see which version is installed by doing `composer show`

**Comment by vladimirkr** [comment]
doctrine/data-fixtures                v1.2.2            
doctrine/orm                              v2.5.6           
nelmio/alice                               v3.0.0-RC.1
hautelook/alice-bundle              v2.0.0-beta.4
nelmio/alice                               v3.0.0-RC.1
theofidry/alice-data-fixtures       v1.0.0-beta.5

**Comment by theofidry** [comment]
Closed via #368
