### ISSUE TITLE
[v1.x] Fixtures loading depends on filesystem 

### ISSUE THREAD

**Issue by magnetik** [hautelook/AliceBundle#298]
Hi,

I'm loading two fixtures files of two entites that have a ManyToOne, but depending on the fixtures loading order (that seems not forced), loading the fixtures requires me to add `cascade={"persist"}` on one side.

Example:

```
//A.php
class A
{
}

//B.php
class B
{
  public function __construct(A $a = null) {
    $this->a = $a;
  }
  /*
   * @ORM\ManyToOne(targetEntity="A")
   */
  protected $a;
}
```

Fixtures:
```
//a.yml
A:
  a_1: ~

//b.yml
B:
  b_1:
    __construct: ["@a_1"]
```

When `a.yml` is loaded first it works, but when `b.yml` is loaded first, doctrine raises an error because `a_1` is not already persisted.

On a machine `a.yml` first, and on another `b.yml` is loaded first.

Shouldn't the order be enforced by the bundle?

**Comment by theofidry** [comment]
If you need to enforce an order you should do it yourself, as there is easy way to know in advance what that order should be.

I'm sorry I can't recall exactly how you should do it in 1.x, but it should be more straightforward in 2.x.

**Comment by lordjancso** [comment]
@theofidry I have the same question but with yml and php fixtures mixed togather. So I have a couple of yml files (with simple fixture logic) and some php files (with more complex fixture logic - I have to do a lot of math so php was a better solution), and I'm getting the "Could not find the fixture ..." error message.
And its because of this line of code in my php fixture:
```
'group' => '@Group'.($c % 20),
```
The groups would be created with yml fixtures and I guess php doesnt check it its existance first.
Could be possible this bundle checks the dependency between yml fixtures only?

**Comment by theofidry** [comment]
I didn't double check in 1.x, you can check by doing step by step debugging to see in what order the files are loaded. In 2.x the file type definitely doesn't matter.
