### ISSUE TITLE
Modify the default limit of number of attempts for loading fixtures

### ISSUE THREAD

**Issue by Kwadz** [hautelook/AliceBundle#318]
As stated in #314:

> [Alice] retries after and continues until either all the files are loaded **or a limit in the number of passes is reached**.

How to increase the limit? It seems to be 5 by default:

```
Loading files limit of 5 reached. Could not load the following files:
[…] 
```

**Comment by theofidry** [comment]
Oh, I was looking at 2.x and surprisingly it's not a configurable parameter yet. It should be exposed in https://github.com/theofidry/AliceDataFixtures' configuration.

For 1.x (which is your case I guess as in 2.x the default is 15), it's the `loading_limit` configuration parameter. You can either check the bundle `Configuration` file (of 2.x not 1.x) or use the `bin/console debug:config BundleName` command

**Comment by Kwadz** [comment]
Does this means AliceBundle can't be used with large fixtures structures (more that 5 fixtures)?

**Comment by theofidry** [comment]
No, it's 5 _passes_ not 5 fixture files. It means if you have a set of files:

```
- file1.yml
- file2.yml
- file3.yml
- file4.yml
- file5.yml
```

it do a _first pass_ to try to load as many files as possible. Between each file loaded, the result is kept and passed while loading the next file, so in the example above maybe 2 files may fail to load because depended of fixtures declared in a file not loaded yet:

```
successfully loaded:
- file3.yml
- file4.yml
- file5.yml

failed to load:
- file1.yml
- file2.yml
```

Then a _second pass_ is done to try to load `file1.yml` and `file2.yml`. And it keeps going until it either succeeded to load all the files or reached the maximum number of passes.

I think you're more likely to be limited by the ORM which is not meant to load high number of objects than alice itself.

**Comment by Kwadz** [comment]
I wanted to mean the worst case for 5 fixtures. Yes, you right it won't be 5 fixtures. But, let's assume 20 fixtures, if the fixtures are not loaded in the good order for each pass, the probability to reach the limit is very high, right?
When does the incrementation is done and when is it reinitialized (if reinitialized)?

**Comment by theofidry** [comment]
The incrementation is done after a pass is completed (so all files have been attempted to be loaded and the counter is re-initialised for each set of files being loaded.

I didn't do any probability calculation so I can say the probability is high, but the shortest case to encounter is to have `%loading_limit% + 1` files, all depending successively of each other, (`f1.yml` depends on `f0.yml`, `f2.yml` depends on `f1.yml`, etc.) and all in the wrong order.

Provided that in practice:

- You should not have to large set of fixture files (it's a recommendation, I know it's not the case of everyone) because it's hard to maintain + being slow to load (ORM limitation 99% of the time, they are not meant for that)
- There order of the files is random (or sorted lexicographically in 2.x IIRC)

It has not been reported to happen very often, and in case it happens to often for a given set of fixtures the user can feel free to put a higher number (or add a hook to sort himself the files in the right order). I prefer to keep it lower by default as it's "enough" most of the time and a fail-fast is preferable IMO.

**Comment by Kwadz** [comment]
In that case I don't understand why I got the error. Would you be able to see what happens in the  following case _(all files are downloadable in one shot_): https://www.dropbox.com/sh/clv9ly1jejrqasd/AAA1tYdWjMR9JhuMgM-QMB5ja

**Comment by theofidry** [comment]
Aren't they dependent of each other? The `hotel_item_group*` clearly show some dependencies between each of those files

**Comment by Kwadz** [comment]
Yes `booking`  and `hotel_item_group` are. In this case should we also populate `bookings` in `hotel_item_group`?

```php
abstract class AbstractBooking // booking
{
    /**
     * @ORM\ManyToOne(targetEntity="Genius\Model\Entity\AbstractItemGroup", inversedBy="bookings")
     * @ORM\JoinColumn(name="item_group_id", referencedColumnName="id", nullable=false)
     */
    protected $itemGroup; 
}

```

```php
abstract class AbstractItemGroup // hotel_item_group
{
    /**
     * @ORM\OneToMany(targetEntity="\Genius\Model\Entity\AbstractBooking", mappedBy="itemGroup")
     */
    protected $bookings;
}
```

**Comment by theofidry** [comment]
I think it's fine, if you need to increase the loading limit just increase it :)
