### ISSUE TITLE
Hard dependency on logger service

### ISSUE THREAD

**Issue by curry684** [hautelook/AliceBundle#373]
When running command in a library with barebones Symfony included:

> PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "hautelook_alice.loader.doctrine_orm_loader" has a dependency on a non-existent service "logger". in xxxxx/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:31

The service has a hard unconditional dependency on the `logger` service, which is not present by default. Given the upcoming Symfony 4.0 and Flex releases which actually encourage barebones installs this will become more relevant soon.

**Comment by theofidry** [comment]
Indeed, I think this should be made optional either by making the logger optional or requiring the PSR logger and registering a null logger if no logger is provided.

**Comment by curry684** [comment]
Actually both   😉

**Comment by theofidry** [comment]
Well if a logger is always registered (the null one), the first option is useless. I actually tend to prefer that second option as I particularly dislike to always have if statements everywhere to check if the logger is set and I don't like to instantiate it in the constructor.

Actually the PSR ships with the NullLogger, so that makes things even easier.
