### ISSUE TITLE
grabs all parameters

### ISSUE THREAD

**Issue by croensch** [hautelook/AliceBundle#468]
Hello, i use the https://github.com/incompass/aws-secrets-bundle to retrieve some secrets. Since i don't want to call the SDK in my tests i came up with lazy-loading schema.
A parameter that is defined for doctrine like that:
```yaml
# config/packages/doctrine.yaml
parameters:
  fetch_rds_password: '%env(aws:FETCH_RDS_PASSWORD)%'
```
It is only loaded when it is actually requested. So in prod i may do:
```bash
export FETCH_RDS_PASSWORD=app/prod/rds,password
export DATABASE_URL=mysql://u:%fetch_rds_password%@h:3306/s
```
While in dev/test i have none of that. The parameter goes unused.
This works with `bin/console doctrine:schema:validate` and the UI in general.

So far i've only found the `hautelook:fixtures` commands to load every parameter, which brings the command to crash since the underlying ENV var is not defined. Is it possible / wanted / accepted that bundles grab every parameter when they want to?
https://github.com/hautelook/AliceBundle/blob/205d10eeb0a5e15e1f5806510e9108d548b6cd59/src/Loader/DoctrineOrmLoader.php#L124

Because then i would need another approach...

**Comment by theofidry** [comment]
My understanding of your issue is that it was not failing in dev/test before because this parameter is lazy loaded, so even though it was not defined, the issue goes unnoticed as long as the parameter is not loaded.

To me this is more a problem with your code: `$application->getKernel()->getContainer()->getParameterBag()->all()` is quite generic and I don't think you should expect it to fail under any circumstances.

Maybe though, an easy fix is to actually declare one fake `fetch_rds_password` in dev/test;

```yaml
# doctrine_test.yml
parameters:
  fetch_rds_password: ~
```

**Comment by croensch** [comment]
The php code was quoted from AliceBundle but ok. I guess as long as symfony provides the ParameterBag::all() method i should not expect parameters to be lazy loading or resolving.
So i moved my dynamic parameter into `config/packages/prod/doctrine.yaml` where it is used.

**Comment by theofidry** [comment]
The example in the doc is to show that using env parameters works. Making
sure that such parameters or env variable is always available is your
responsibility however as it entirely depends on your setup
