### ISSUE TITLE
Load Fixtures in a Test environment with APP_ENV=prod

### ISSUE THREAD

**Issue by leroy0211** [hautelook/AliceBundle#475]
We are running an application and have 4 environments for this application. 
* A local development environment
* A test environment (APP_ENV=prod, APP_DEBUG=1)
* An Acceptance environment (APP_ENV=prod, APP_DEBUG=0)
* A production environment (APP_ENV=prod, APP_DEBUG=0)

Because the test, acceptance and production are all running APP_ENV=prod it is not possible to load the fixtures. We only need the fixtures in the test environment btw. 
This test environment is not the test env of symfony, but following the DTAP standards. 

Is there any way of loading the fixtures in an environment like above? Or maybe to export the fixtures in an `.sql` file so we can load them manually. 

Some background:
We are running multiple applications on openshift (/kubernetes), so all images are built using the production environment setting. The only installed composer packages are the production packages (`--no-dev`).

**Comment by theofidry** [comment]
IMO your issue is more a pipeline/dependency one than anything.

- If you want to be able to load fixtures, which means relying on this bundle, in prod mode, Alice need to be a prod dependency, not a dev one.
- If it's just about having fixtures for some QA tests or a demo, you could I guess create & populate the test DB and export that DB (relying on your DB, e.g. mysqldump or pgdump) which you could load for your QA/demo

**Comment by leroy0211** [comment]
Yes, that's what I thought. It's kinda for a demo yes. 

So there is nothing available, or in future scope of this bundle to dump the fixtures to an sql file? Because that would automating the export a lot easier.

**Comment by theofidry** [comment]
I don't think this bundle should try to do that: any export easily requires tempering of export settings which greatly change from a vendor to another. The process to lead to the export of that SQL file is also likely to be extremely specific.

In other words: this is something that is most likely better solved on a case by case basis rather than trying to abstract it some way in the bundle.
