### ISSUE TITLE
Hardcoded object manager persister

### ISSUE THREAD

**Issue by rivaros** [hautelook/AliceBundle#489]
DoctrineOrmLoader.php Ln. 135
Returns us hardcoded object of class ```Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister```

```
    protected function createPersister(EntityManagerInterface $manager): PersisterInterface
    {
        return new ObjectManagerPersister($manager);
    }
```

I was trying to decorate service fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister

but gave up :)

**Comment by theofidry** [comment]
It's a protected function so you can extend it.

I'm not too happy with how AliceBundle is right now... The root of the issue is that you can pass a couple of options which configure which services are used or how they are used. Hence we actually need to bypass quite a few services registered by AliceDataFixtures which makes it hard and fragile.

I however could not take a deep look on how this could be solved

**Comment by nirix** [comment]
@theofidry 
> It's a protected function so you can extend it.

We cannot extend a `final` class:
> PHP Fatal error:  Class MyDoctrineOrmLoader may not inherit from final class (Hautelook\AliceBundle\Loader\DoctrineOrmLoader)

We are using a modified `ObjectManagerPersister` and need to use it in the HauteLook/AliceBundle for consistency but are unable to due to the above.

**Comment by theofidry** [comment]
Hm that's definitely a mistake, feel free to do a PR to remove it

**Comment by theofidry** [comment]
`DoctrineOrmLoader ` is no longer private so this should not be a problem anymore
