### ISSUE TITLE
Impossible to disable including fixtures from bundles with `hautelook:fixtures:load` command

### ISSUE THREAD

**Issue by Metalrex100** [hautelook/AliceBundle#495]
My fixtures places in `tests/Fixtures` directory and I have problem with other bundles, like `nelmio/cors-bundle`, because it also has `tests/Fixtures` with `ProviderMock.php` class, which triggers error. (`ProviderMock.php` has different from implemented interface return type and php 7.2 triggers error)

Of course, I can hack this problem by adding only 1 random bundle to bundles list, but since I use symfony-flex, there is no need for me in loading fixtures from bundles, so it would be cool if there was some flag like `--no-bundles`.

A can prepare merge-request if it is ok for you.

**Comment by theofidry** [comment]
Hi, what interface are you referring to for `ProviderMock.php`? Is it about HautelookAliceBundle 1.x?

**Comment by Metalrex100** [comment]
@theofidry Hello!
In config as path to fixtures I specified `tests/Fixtures`.
When I run `hautelook:fixtures:load` command without `bundle` flag, it iterates through all external (vendor) bundles which are specified in `config/bundles.php` file and tries to find fixture files in path `tests/Fixtures` in each bundle.

Nelmio Cors bundle has `tests/Fixtures` directory, which contains file with `ProviderMock.php`, so fixture loader tries to load this file, but php triggers error because of problems with `ProviderMock.php`.

The main idea is that I don’t want to load fixtures from any external bundles, but currently it’s impossible.

**Comment by theofidry** [comment]
Indeed it doesn't really make sense to load third-party bundles IMO... And if you want to you can always include them manually (by creating fixture file and refer to the fixtures you want to load).

Another error is attempting to load `ProviderMock.php` which is definitely not possible...

So there two issues here. But can you confirm this is `2.x` not `1.x`?

**Comment by Metalrex100** [comment]
@theofidry I'm using version `2.6.2`.

As for me, if you want to load fixtures from other bundles (with `hautelook:fixtures:load` command), it is better to specify them directly. If no bundles specified, then only main app fixtures will be loaded. Currently if no bundles specified, loader will try to load fixtures from all bundles it found.

I guess the second issue is not a problem of your bundle, because your bundle only tries to load all files from each bundle specified in my `config/bundles.php` file.

If I will change `hautelook_alice.fixtures_path` param value from `tests/Fixtures` to `fixtures` (default path for symfony-flex applications), then there will be no problem with `ProviderMock.php` file of Nelmio Cors bundle.

Tell me please if my description was not really clear for you :)

**Comment by theofidry** [comment]
>Currently if no bundles specified, loader will try to load fixtures from all bundles it found.

I'm a bit split between trying to move away from this and allow multiple fixture directories (hence you could always manually add additional paths for some bundles) and attempting to "correct" it by looking only for the app bundles not all the bundles (but it's hard to distinguish which one is which).

>I guess the second issue is not a problem of your bundle, because your bundle only tries to load all files from each bundle specified in my config/bundles.php file.

Yes and no: it happens because of that, but I don't think having an undesired file should break things. Maybe it could be skipped and logged as such if you are displaying a verbose mode with the command that way you do get a notification of some sorts that this file was not loaded. This would be more friendly while still warning you in case this was a file you wanted to load and was not due to an error

In both cases though: it's non-trivial changes and realistically I'm unlikely to work on them :/ So PRs are welcomed :)

**Comment by Metalrex100** [comment]
@theofidry as for me the fastest solution will be to add flag `--no-bundles` to `hautelook:fixtures:load` command and also to add same parameter to `DoctrineOrmLoader.php::load` method with default `false` value (to not break backward capability).

example of changes in `DoctrineOrmLoader.php::load` method with new param:
```
if ($noBundles) {
    $bundles = $this->bundleResolver->resolveBundles($application, $bundles);
}
```

What do you think about such solution?

**Comment by theofidry** [comment]
Looks good to me. 

I would actually also love it a step further. An idea would be that your `--no-bundles`:

in 3.x:

- `--no-bundles` is deprecated: we keep it for easing the upgrade

in 2.x:

- `--no-bundles`: change the behaviour to what you described
- when no `--no-bundles` flag is found, we add a deprecation notice recommending to leverage `hautelook.root_dirs` instead of specify the third-party bundle fixtures
