### ISSUE TITLE
Fixtures loading command is not in good folder

### ISSUE THREAD

**Issue by X-PRIME** [hautelook/AliceBundle#69]
Hi,

It seems the folder containing the command allowing to load fixtures is not at the right path so SF2 doesn't detect the command and doesn't register it...

It will be simpler to you to correct it, than to me to do a PR.

Thank for this great bundle.

**Comment by theofidry** [comment]
Hi @X-PRIME.

Would you mind giving me more details? Which version are you using?

If you check [`Tests/SymfonyApp`](https://github.com/hautelook/AliceBundle/tree/master/Tests/SymfonyApp), you'll see an example of a Symfony application to which the bundle is registered (to launch the console, simply do `php console`, the console file is placed at the root of the bundle). This version (of the SymfonyApp) is dedicated for tests so it may not follow some best practices, nonetheless it may help you.

On my side the bundle is running fine, so if you keep having the problem, try to tell me a bit more or provide me a link!

Hoping it solves your issue.

**Comment by Ender33** [comment]
Sorry for the late answer.
Was with my company's account so let's continue with mine.

My problem is when I install the bundle following the doc, and then I run php app/console from my project's root, the hautelook:fixtures:load command doesn't exist and does not exist. And I think it's normal because your command folder is not at the root of the bundle so SF2 doesn't detect it.
I could register manually the command, but I suppose it's not the goal because it's not mentioned in your doc...

Is there a step I forgot ?
Thanks for your help and reactivity.

**Comment by theofidry** [comment]
If you run a `php app/console debug:config`,  do you see `HautelookAliceBundle hautelook_alice`?

Indeed the command is not placed at the root folder, but it should not cause any problem as the command is registered as a service, cf. [the command declaration](https://github.com/hautelook/AliceBundle/blob/master/Resources/config/services.xml#L34-L41).

**Comment by Ender33** [comment]
OK, i found the problem :  composer config problem.

Thank you for your help and sorry for inconvienence?
You can close this issue.

**Comment by theofidry** [comment]
Good news :)
